### ISSUE TITLE
Undefined symbol: _OBJC_CLASS_$_GameServicesHelper in Godot 4

### ISSUE THREAD

**Issue by i-Madsen** [sjc/godot-game-services#4]
Hi there,

I've been trying to update your plugin to use with Godot 4 (as well as add additional GameCenter calls), but I'm running into some problems in XCode. (My fork: [https://github.com/i-Madsen/godot4-game-services])

I'm able to build the plugin with my changes into a static library and copy it into my Godot project and export it, but then I get these errors when trying to build that in XCode:

ld: warning: Could not find or use auto-linked framework 'CoreAudioTypes'
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_GameServicesHelper", referenced from:
      objc-class-ref in gameservices.a(gameservices.o)
  "ClassDB::bind_methodfi(unsigned int, MethodBind*, char const*, Variant const**, int)", referenced from:
      GameServices::_bind_methods() in gameservices.a(gameservices.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Any ideas what would cause this?

**Comment by sjc** [comment]
Could you provide a description of how you're building the plugin?

**Comment by sjc** [comment]
Which Godot header files are you using?

**Comment by sjc** [comment]
The root issue seems to be that the `scons` build isn't including `GameServicesHelper.m`, mainly because it's only gathering `.mm` (Objective-C++) source files. I'm not sure why its behaviour has changed, but I'm certain it was working before.

I suggest renaming `GameServicesHelper.m` to `GameServicesHelper.mm`. After doing this and rebuilding the missing classes are now in the library:

```
% nm gameservices.debug.a | grep Helper
gameservices.debug.a(GameServicesHelper.o):
0000000000000420 t -[GameServicesHelper .cxx_destruct]
000000000000040c t -[GameServicesHelper currentLeaderboardID]
0000000000000194 t -[GameServicesHelper gameCenterViewControllerDidFinish:]
0000000000000000 t -[GameServicesHelper initWithGameServices:]
0000000000000044 t -[GameServicesHelper presentViewController:]
0000000000000118 t -[GameServicesHelper presentViewController:forLeaderboardID:]
00000000000003fc t -[GameServicesHelper services]
0000000000000418 t -[GameServicesHelper setCurrentLeaderboardID:]
0000000000000404 t -[GameServicesHelper setServices:]
00000000000004d0 S _OBJC_CLASS_$_GameServicesHelper
0000000000000fbc S _OBJC_IVAR_$_GameServicesHelper._currentLeaderboardID
0000000000000fb8 S _OBJC_IVAR_$_GameServicesHelper._services
00000000000004f8 S _OBJC_METACLASS_$_GameServicesHelper
0000000000000d10 s __OBJC_$_INSTANCE_METHODS_GameServicesHelper
0000000000000df0 s __OBJC_$_INSTANCE_VARIABLES_GameServicesHelper
0000000000000e38 s __OBJC_$_PROP_LIST_GameServicesHelper
0000000000000cb0 s __OBJC_CLASS_PROTOCOLS_$_GameServicesHelper
0000000000000ea0 s __OBJC_CLASS_RO_$_GameServicesHelper
0000000000000cc8 s __OBJC_METACLASS_RO_$_GameServicesHelper
00000000000001ec t ___56-[GameServicesHelper gameCenterViewControllerDidFinish:]_block_invoke
                 U _OBJC_CLASS_$_GameServicesHelper
```

**Comment by i-Madsen** [comment]
Awesome, that did the trick and got it to build.

Thank you for the help!
